### ISSUE TITLE
关于模板的几点意见

### ISSUE THREAD

**Issue by sikouhjw** [hoganbin/CMC-Solutions#1]
1. 内容与形式分离
这是演示文档里的代码
https://github.com/hoganbin/CMCThesis/blob/58a07f95c608f3725183ca93db3eb7d820d61d9a/CMC.tex#L96
这是`\ws`宏的定义
https://github.com/hoganbin/CMCThesis/blob/58a07f95c608f3725183ca93db3eb7d820d61d9a/cmcthesis.cls#L294-L295
很明显演示文档与宏的定义部分是重叠的、无用的，这样会给使用者徒增困扰
2. 将页面设计成这样是为了什么目的？
https://github.com/hoganbin/CMCThesis/blob/58a07f95c608f3725183ca93db3eb7d820d61d9a/cmcthesis.cls#L186-L194
3. 不应该修改`cls`文件
https://github.com/hoganbin/CMCThesis/blob/58a07f95c608f3725183ca93db3eb7d820d61d9a/cmcthesis.cls#L454-L530
如果要修改`第十届`这个关键词，还需要去修改`cls`，这是不应该的，这些应该当成选项在导言区设置，此外`微信公众号：八一考研数学竞赛`也是不应该放`cls`里的

**Comment by sikouhjw** [comment]
4. 建议把pdf文件放入`releases`而不是放`code`里

**Comment by hoganbin** [comment]
第3点我认为还是很有道理，考虑到用户的需要，确实需要把cls几个重要接口放在主文件中，并新增了subname与author两个接口，页面大小是根据试卷需求而这样设计了，后面再作相关修改，那个ws重定义中已经在主文件把\bf删了，非常感谢

**Comment by CamuseCao** [comment]
已经放了很久了，关闭吧。
